version: '3.4'

services:
  auctionsystem:
    image: auctionsystem:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
